apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    matchLabels:
      app: accounts
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: gabriellopes00/morpheus-accounts:v1

---

apiVersion: v1
kind: Service
metadata: 
  name: accounts-srv
spec:
  type: ClusterIP
  selector:
    app: accounts
  ports:  
  - name: api-port
    port: 7765
