apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  labels:
    app: events
spec:
  selector:
    matchLabels:
      app: events
  replicas: 1
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: gabriellopes00/morpheus-events:v1

---
apiVersion: v1
kind: Service
metadata:
  name: events-srv
spec:
  type: ClusterIP
  selector:
    app: events
  ports:
    - name: api-port
      port: 4422
