apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  selector:
    matchLabels:
      app: mailer
  replicas: 1
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: gabriellopes00/morpheus-mailer:v1

---

apiVersion: v1
kind: Service
metadata: 
  name: mailer-srv
spec:
  selector:
    app: mailer
  type: ClusterIP
  ports:  
  - name: smtp-port
    port: 2525
