CREATE TABLE IF NOT EXISTS "categories" (
    id UUID UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE IF EXISTS "events" ADD COLUMN IF NOT EXISTS "category_id" UUID DEFAULT NULL;
ALTER TABLE IF EXISTS "events" ADD CONSTRAINT fk_category FOREIGN KEY (category_id) 
REFERENCES categories (id) ON DELETE SET NULL;