CREATE TABLE IF NOT EXISTS "subjects" (
    id UUID UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE IF EXISTS "events" ADD COLUMN IF NOT EXISTS "subject_id" UUID DEFAULT NULL;
ALTER TABLE IF EXISTS "events" ADD CONSTRAINT fk_subject FOREIGN KEY (subject_id) 
REFERENCES subjects (id) ON DELETE SET NULL;