version: '3.9'

services:
  rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:3-management
  restart: always
  environment:
    RABBITMQ_ERLANG_COOKIE: 83da6479156341769d743dc1f9c7ba98
    RABBITMQ_DEFAULT_USER: rabbitmq
    RABBITMQ_DEFAULT_PASS: rabbitmq
    RABBITMQ_DEFAULT_VHOST: /
  ports:
    - '15672:15672'
    - '5672:5672'
  networks:
    - mailer

  mailer:
    container_name: mailer
    restart: always
    depends_on:
      - rabbitmq
    build: .
    networks:
      - mailer

networks:
  mailer:
    driver: bridge
