CREATE TABLE IF NOT EXISTS "accounts" (
  "id" UUID NOT NULL UNIQUE,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "password" VARCHAR(255) NOT NULL,
  "avatar_url" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,

  PRIMARY KEY ("id")
);