DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ACCOUNT_GENDER') THEN
        CREATE TYPE ACCOUNT_GENDER AS ENUM ('male', 'female', 'unspecified');
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS "accounts" (
  id UUID NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  document VARCHAR(14) NOT NULL UNIQUE,
  phone_number VARCHAR(15) NOT NULL UNIQUE,
  gender ACCOUNT_GENDER NOT NULL,
  avatar_url VARCHAR(255) NOT NULL,
  birth_date TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

  PRIMARY KEY (id)
);