apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    matchLabels:
      app: accounts
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: gabriellopes00/morpheus-accounts:latest
          resources:
            requests:
              cpu: "0.03"
              memory: 10Mi
            limits:
              cpu: "0.03"
              memory: 15Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  selector:
    matchLabels:
      app: mailer
  replicas: 1
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: gabriellopes00/morpheus-mailer:latest
          resources:
            requests:
              cpu: "0.03"
              memory: 10Mi
            limits:
              cpu: "0.03"
              memory: 15Mi