apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accounts-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accounts
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mailer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailer
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75