import { Grid } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import EventCard from '../components/event-card'
import NavBar from '../components/nav-bar'
import { SideBar } from '../components/side-bar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid container justifyContent="center" gap={4}>
        <Grid item xs={2}>
          <SideBar />
        </Grid>
        <Grid container item xs={8} justifyContent="center" gap={2}>
          {Array.from(Array(9)).map((_, index) => (
            <Grid item key={index}>
              <EventCard />
            </Grid>
          ))}
        </Grid>
      </Grid>
    </>
  )
}

export default Home
