import { Grid } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import EventCard from '../components/event-card'
import NavBar from '../components/nav-bar'
import { SideBar } from '../components/side-bar'
import { EventFilterProvider } from '../contexts/event-filter-context'

const Home: NextPage = () => {
  return (
    <EventFilterProvider>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid
        container
        justifyContent="space-between"
        height={'calc(100vh - 69px)'}
      >
        <Grid item xs={3}>
          <SideBar />
        </Grid>

        <Grid
          container
          item
          xs={8}
          justifyContent="center"
          gap={2}
          sx={{ overflowY: 'scroll', height: 'calc(100vh - 69px)' }}
        >
          {Array.from(Array(9)).map((_, index) => (
            <Grid item key={index}>
              <EventCard
                title="Lizard"
                description="Lizards are a widespread group of squamate reptiles, with over 6,000
          species, ranging across all continents except Antarctica"
                imageUrl="https://source.unsplash.com/random"
              />
            </Grid>
          ))}
        </Grid>
      </Grid>
    </EventFilterProvider>
  )
}

export default Home
