FROM golang:1.17.0 AS builder

WORKDIR /go/src/morpheus/events

COPY go.* ./
COPY Makefile .
COPY .env .

RUN make install

COPY cmd cmd
COPY config config
COPY domain domain
COPY application application
COPY framework framework
RUN make build
EXPOSE 4422
CMD /go/src/morpheus/events/app